name: desktop_flag_manager
description: "A simple tool to manage desktop flags to apps that don't fully support Wayland yet"

version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  